name: Compile Backgrounds
on: push

jobs:
  pester-test:
    name: Compile
    runs-on: windows-latest
    steps:
      - name: Run
        working-directory: .
        run: fbt.cmd icons proto dolphin_internal dolphin_ext resources
